apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: config-app-ingress
spec:
  rules:
    - host: dev.floraum.co.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: config-app-service
                port:
                  number: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
      tier: app
  template:
    metadata:
      labels:
        app: config
        tier: app
    spec:
      containers:
        - name: config
          image: docker.io/kikiki0611/conf-app:latest
          ports:
            - containerPort: 8888
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: config-app-service
spec:
  ports:
    - port: 8888
      protocol: TCP
  selector:
    app: config
    tier: app
